language: python
python:
  - 3.3
  - 3.4
  - 3.5

before_install:
    - pip install cython
install: 
    - python setup.py install

# Note that we skip the math module because it requires cython
script: py.test --ignore tests/test_math.py 

notifications:
  email:
    on_success: change
    on_failure: always
