language: python
python:
  - 3.3
  - 3.4
  - 3.5
before_install:
    - pip install cython
install: 
    - python setup.py install
script: py.test
notifications:
  email:
    recipients:
    on_success: change
    on_failure: always
